export const AEL_ERROR_CODES = {
  CONFIG_UNKNOWN_FIELD: 'AEL_CONFIG_UNKNOWN_FIELD',
  CONFIG_INVALID_SCHEMA_VERSION: 'AEL_CONFIG_INVALID_SCHEMA_VERSION',
  CONFIG_DUPLICATE_ID: 'AEL_CONFIG_DUPLICATE_ID',
  CONFIG_INVALID_THRESHOLD: 'AEL_CONFIG_INVALID_THRESHOLD',
  CONFIG_NON_FINITE_NUMBER: 'AEL_CONFIG_NON_FINITE_NUMBER',
  CONFIG_MISSING_GRADER: 'AEL_CONFIG_MISSING_GRADER',
  CONFIG_EMPTY_ARMS: 'AEL_CONFIG_EMPTY_ARMS',
  CONFIG_INVALID_TELEMETRY_QUALITY: 'AEL_CONFIG_INVALID_TELEMETRY_QUALITY',
  CONFIG_INCONSISTENT_OUTCOME_MODE: 'AEL_CONFIG_INCONSISTENT_OUTCOME_MODE',
  CONFIG_INVALID_PHASE_SESSION: 'AEL_CONFIG_INVALID_PHASE_SESSION',
  CONFIG_INVALID_BLINDED_RUBRIC: 'AEL_CONFIG_INVALID_BLINDED_RUBRIC',
  CONFIG_VALIDATION_FAILED: 'AEL_CONFIG_VALIDATION_FAILED',
} as const;

export type AelErrorCode = (typeof AEL_ERROR_CODES)[keyof typeof AEL_ERROR_CODES];
